### PR TITLE
Updated SKCSKEINCOIN logo + Fix display of the logo in https://github.com/BlockABC/eos-tokens

### PR DESCRIPTION
**Pull request by phennaux**
### Please check the following items to ensure a successful verification of EOS Token info:

**.json and .png file checklists**
- [x] All new token files are placed under a folder named with it's contract name
- [x] Same name for both .json and .png (All Caps), with <TOKEN_NAME>.json/<TOKEN_NAME>.png format
- [x] logo dimensions: 120*120 px
- [x] logo background: Transparent
- [x] Do not modify `tokens.json`

### CODE REVIEW

**Comment by phennaux** [comment]
Telegram contact @ovgysel

**Comment by zgayjjf** [comment]
@phennaux Please resolve conflict first

**Comment by phennaux** [comment]
@zgayjjf I see that there is a conflict with both SKCSKEINCOIN.json and SKCSKEICNOIN.png, but I don't have write acess to resolve conflicts

**Comment by zgayjjf** [comment]
I noticed that there is no difference between your code and that on github, so you don't have to make any changes.

Feel free to reopen this PR.

**Pull request closed without merging**
