### PR TITLE
Re-order format

### PR DESCRIPTION
**Pull request by koheitokumasu**

### CODE REVIEW

**Comment by koheitokumasu** [comment]
Contact : support@angelium.net

**Comment by zgayjjf** [comment]
There is no logo image in your commit. Did you forget to upload one?

**Comment by koheitokumasu** [comment]
@zgayjjf oh, this is our logo image.
I couldn't find where to comitt...

anl

**Comment by zgayjjf** [comment]
OK...I will handle that for you.
But please do learn how to use github later if you are a developer.

**Comment by koheitokumasu** [comment]
@zgayjjf Thanks, sorry I was accessing from different workspace this time and using just a browser, then I couldn't see how. Next time, I'll access via git. Thanks,

**Pull request merged**
